name: Run script weekly

on:
  schedule:
    - cron: '0 1 * * 4'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: false
    - uses: actions/setup-python@v5
    - run: pip install -r requirements.txt
    - run: pytest tests/
    - run: |
       git config --global user.name "github-actions[bot]"
       git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - run: |
       echo "Existing files:"
       ls -l "Custom Rosters"

    - run: |
       echo "Checking Custom Rosters before Python script..."
       ls -l "Custom Rosters"
    - run: python basketball_gm_league_player_file_generator.py

    - run: git add "Custom Rosters/*"
    - run: git diff --cached --quiet || git commit -m "Update JSON file"

    - name: Push changes 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin HEAD:main
