name: Run script weekly

on:
  schedule:
    - cron: '0 1 * * 4'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: pip install -r requirements.txt
    - run: pytest tests/
    - run: basketball_gm_league_player_file_generator.py
    - run: git config --global user.name "KingKO04"
    - run: git config --global user.email "mancity4everafter@gmail.com"
    - run: git add "Custom Rosters/*"
    - run: git diff --cached --quiet || git commit -m "Update JSON file"
    - run: |
       git push origin HEAD:main
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
